name: build

on:
  push:
  workflow_dispatch:

jobs:
  build-kindest-crio-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: kindest-base-crio

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.4'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Kubernetes
        uses: actions/checkout@v4
        with:
          repository: kubernetes/kubernetes
          path: src/k8s.io/kubernetes/
          fetch-tags: true
          ref: v1.27.8
          filter: 'blob:none'

      - name: Checkout Kind
        uses: actions/checkout@v4
        with:
          repository: kubernetes-sigs/kind
          path: kind

      - name: Extract metadata (tags, labels) for Base image
        id: meta-base
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: kind/images/base
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            GO_VERSION=1.20.4
          tags: ${{ steps.meta-base.outputs.tags }}
          labels: ${{ steps.meta-base.outputs.labels }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - name: Extract metadata (tags, labels) for Node image
        id: meta-node
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/kindest-node-crio

      - name: Build and push node image
        run: |
          echo "Base Image Tag: ${{ steps.meta-node.outputs.tags }}"
          echo "Node Image Tag: ${{ steps.meta-node.outputs.tags }}"
          curl -Lo ./kind-bin https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind-bin
          sudo mv ./kind-bin /usr/local/bin/kind
          sudo apt update && sudo apt install build-essential jq -y
          kind build node-image --arch amd64 --base-image ${{ steps.meta-base.outputs.tags }} --image ${{ steps.meta-node.outputs.tags }} ${GOPATH}/src/k8s.io/kubernetes --verbosity 10


      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
