name: build

on:
  push:
  workflow_dispatch:

jobs:
  build-kindest-base-crio:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: kindest-base-crio

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Kubernetes
        uses: actions/checkout@v4
        with:
          repository: kubernetes/kubernetes
          path: kubernetes

      - name: Checkout Kind
        uses: actions/checkout@v4
        with:
          repository: kubernetes-sigs/kind
          path: kind

      - name: Debug
        run: |
          tree -d -L 2

      - name: Build and push base image
        uses: docker/build-push-action@v5
        with:
          context: kind/images/base
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            GO_VERSION=1.20.4
          tags: ghcr.io/${{ github.repository }}:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Build and push node image
        run: |
          echo "Arch: $(uname -m)"
          echo "Base Image Tag: ${{ steps.meta.outputs.tags }}"
